services:
  - type: web
    name: ridex360-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "python manage.py migrate && python manage.py ensure_superuser && python manage.py ensure_org_admin && python manage.py seed_demo && gunicorn ridex360.wsgi"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_SUPERUSER_USERNAME
        value: RideX360
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@ridex360.app
      - key: DATABASE_URL
        fromDatabase:
          name: ridex360-db
          property: connectionString
      - key: ORG_ADMIN_USERNAME
        value: orgadmin1
      - key: ORG_ADMIN_PASSWORD
        sync: false

databases:
  - name: ridex360-db
    plan: free