# Generated by Django 6.1 on 2026-08-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='alt_route_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='traffic_detected',
            field=models.BooleanField(default=False),
        ),
    ]





    