# Generated by Django 6.1 on 2026-08-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_trip_alt_route_active_trip_traffic_detected'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripstop',
            name='scheduled_arrival_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]